<a href="https://colab.research.google.com/github/swathi040/swathi/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import random

print("Hi welcome to the game, This is a number guessing game.\nYou got 7 chances to guess the number. Let's start the game")

number_to_guess = random.randrange(100)

chances = 7

guess_counter = 0

while guess_counter < chances:

    guess_counter += 1
    my_guess = int(input('Please Enter your Guess : '))

    if my_guess == number_to_guess:
        print(f'The number is {number_to_guess} and you found it right !! in the {guess_counter} attempt')
        break

    elif guess_counter >= chances and my_guess != number_to_guess:
        print(f'Oops sorry, The number is {number_to_guess} better luck next time')

    elif my_guess > number_to_guess:
        print('Your guess is higher ')

    elif my_guess < number_to_guess:
        print('Your guess is lesser')


Hi welcome to the game, This is a number guessing game.
You got 7 chances to guess the number. Let's start the game
Please Enter your Guess : 3
Your guess is lesser
Please Enter your Guess : 7
Your guess is lesser
Please Enter your Guess : 100
Your guess is higher 
Please Enter your Guess : 1000
Your guess is higher 
Please Enter your Guess : 50
Your guess is lesser
Please Enter your Guess : 80
Your guess is higher 
Please Enter your Guess : 1000000
Oops sorry, The number is 70 better luck next time


In [2]:
import numpy as np
# Step 1: Read an array from the user
# Let's assume the user enters 9 elements for the matrix
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [3]:
# Step 2: Display the array
print("\nOriginal Array:")
print(a)



Original Array:
[1 2 3 4 5 6 7 8 9]


In [4]:
# Step 3: Resize the array to a 3x3 matrix
a = a.reshape(3, 3)
print("\nResized to 3x3 Matrix:")
print(a)


Resized to 3x3 Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Step 4: Create a random 3x3 matrix
b = np.random.randint(1, 10, (3, 3))  # Generate random integers between 1 and 9
print("\nRandom 3x3 Matrix:")
print(b)



Random 3x3 Matrix:
[[2 3 4]
 [4 6 2]
 [4 2 6]]


In [6]:
# 5.1 Matrix Addition
sum = np.add(a, b)
print("\nMatrix Addition (A + B):")
print(sum)
# 5.2: Matrix Subtraction
sub = np.subtract(a, b)
print("\nMatrix Subtraction (A - B):")
print(sub)



Matrix Addition (A + B):
[[ 3  5  7]
 [ 8 11  8]
 [11 10 15]]

Matrix Subtraction (A - B):
[[-1 -1 -1]
 [ 0 -1  4]
 [ 3  6  3]]


In [7]:
# 5.1 Matrix Addition
sum = np.add(a, b)
print("\nMatrix Addition (A + B):")
print(sum)
# 5.2: Matrix Subtraction
sub = np.subtract(a, b)
print("\nMatrix Subtraction (A - B):")
print(sub)



Matrix Addition (A + B):
[[ 3  5  7]
 [ 8 11  8]
 [11 10 15]]

Matrix Subtraction (A - B):
[[-1 -1 -1]
 [ 0 -1  4]
 [ 3  6  3]]


In [8]:
# 5.3: Matrix Multiplication (Element-wise product)
mul = np.dot(a, b)  # or you can use a @ b for matrix multiplication
print("\nMatrix Multiplication (a * b):")
print(mul)



Matrix Multiplication (a * b):
[[22 21 26]
 [52 54 62]
 [82 87 98]]


In [9]:
# 5.4: Cross Product (Only for 3x3 matrices, row-wise)
cross = np.cross(a, b)
print("\nCross Product (Row-wise A x B):")
print(cross)



Cross Product (Row-wise A x B):
[[ -1   2  -1]
 [-26  16   4]
 [ 30  -6 -18]]


In [10]:
# 5.5: Transpose of a matrix
transpose_a = np.transpose(a)
print("\nTranspose of Matrix A:")
print(transpose_a)



Transpose of Matrix A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [11]:
# 5.6: Determinant of Matrix A
det_a = np.linalg.det(a)
print("\nDeterminant of Matrix A:")
print(det_a)



Determinant of Matrix A:
0.0


In [12]:
# 5.7: Inverse of Matrix A
if det_a != 0:  # Inverse exists only if determinant is non-zero
    inv_a = np.linalg.inv(a)
    print("\nInverse of Matrix A:")
    print(inv_a)
else:
    print("\nMatrix A has no inverse (Determinant is zero).")



Matrix A has no inverse (Determinant is zero).


Matplotlib

Signals and System

import numpy as np
import matplotlib.pyplot as plt

In [27]:
# Samling
# step 1: Define the continuous time signal parameters
t_continuous = np.linspace(0, 1, 1000)  # Create a time array from 0 to 1 second with 1000 points for continuous time
frequency = 2  # Frequency of the sine wave in Hertz (5 cycles per second)
continuous_signal = np.sin(2 * np.pi * frequency * t_continuous)  # Generate a continuous sine wave signal

In [25]:
seconds_in_a_day = 24 * 60 * 60
seconds_in_a_day

86400